---

- hosts: webservers

  vars_files:
    - env_vars/general.yml

  roles:
    - ping_test
    - base
    - install_python27
    - apache_httpd
    - { role: vagrant_database, when: (env_setup == 'dev') }

