---

- name: restart mysql
  become: yes
  become_method: sudo
  service:
    name: mysqld
    state: restarted
    enabled: yes

- name: restart mongod
  become: yes
  become_method: sudo
  service:
    name: mongod
    state: restarted
    enabled: yes

